In [1]:
from numpy import random

In [2]:
x = random.choice([3, 5, 7, 9])

print(x)

9


In [3]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 5 7 5]
 [3 9 3 9 5]
 [7 5 5 3 9]]


In [4]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 5 5 7 7 7 7 3 7 7 7 5 5 5 7 3 7 7 3 5 7 5 7 5 7 5 5 7 5 5 3 7 7 7 7 7 7
 3 3 7 3 5 5 7 7 7 7 7 7 5 5 7 7 7 5 5 5 5 7 7 5 5 7 3 7 5 7 7 5 5 7 7 3 7
 7 7 5 5 7 7 7 7 7 7 7 7 7 5 7 7 7 7 7 5 7 5 7 3 3 7]


In [5]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 5 7 7 3]
 [7 3 5 7 7]
 [5 7 7 5 5]]
