In [1]:
from numpy import random

In [2]:
x = random.randint(100)
print(x)

36


In [3]:
x = random.rand()

print(x)


0.011134642023298058


In [4]:

x=random.randint(100, size=(5))

print(x)

[64 40 66 54  2]


In [5]:
x = random.randint(100, size=(3, 5))

print(x)

[[23  0  1 60 14]
 [91 62 27 82 35]
 [ 8 35 99 31 64]]


In [6]:
x = random.rand(5)

print(x)

[0.10684928 0.95688875 0.52971092 0.27234595 0.86288342]


In [7]:
x = random.rand(3, 5)

print(x)

[[0.37457484 0.32785905 0.69816381 0.06412887 0.09146029]
 [0.38588832 0.09026351 0.83831327 0.43134318 0.7071251 ]
 [0.35897691 0.98662412 0.81676013 0.21088249 0.25266828]]
