In [1]:
import numpy as np

In [4]:

arr = np.array([1, 2, 3, 4, 5])

s_arr = np.random.shuffle(arr)

print(arr)
print(s_arr)


[3 5 1 2 4]
None


In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(np.random.permutation(arr))

[1 2 3 4 5]
[5 4 3 2 1]
