In [2]:
import numpy as np

In [4]:
np.random.seed(10)
print(np.random.random())

0.771320643266746


In [28]:
print(np.random.randint(1, 10, 5))

[7 9 8 5 2]


In [38]:
np.random.seed(10)   # Fix the randomness

print(np.random.randint(1, 10, 5))

[5 1 2 1 2]


In [42]:
np.random.seed(10)
print(np.random.randint(1, 10, 5))

np.random.seed(42)
print(np.random.randint(1, 10, 5))

np.random.seed(11)
print(np.random.randint(1, 10, 5))

np.random.seed(10)
print(np.random.randint(1, 10, 5))

[5 1 2 1 2]
[7 4 8 5 7]
[1 2 8 2 8]
[5 1 2 1 2]


In [47]:
np.random.seed(10)
print(np.random.randint(1, 10, 5))
print(np.random.randint(1, 10, 5))
print('\n')

np.random.seed(42)
print(np.random.randint(1, 10, 5))
print(np.random.randint(1, 10, 5))
print('\n')

np.random.seed(11)
print(np.random.randint(1, 10, 5))
print(np.random.randint(1, 10, 5))
print('\n')

np.random.seed(10)
print(np.random.randint(1, 10, 5))
print(np.random.randint(1, 10, 5))

[5 1 2 1 2]
[9 1 9 7 5]


[7 4 8 5 7]
[3 7 8 5 4]


[1 2 8 2 8]
[3 9 1 1 5]


[5 1 2 1 2]
[9 1 9 7 5]
