#### What is an Axis in NumPy?
Think of a NumPy array like a grid of numbers.
* Axis = direction in which you move inside the array.
* Axis 0: moves down the rows (vertical).
* Axis 1: moves across the columns (horizontal).
* Axis 2: moves into/out of the depth (only in 3D arrays).

#### Detailed list showing how concatenate and stack behave with 1D, 2D, and 3D arrays, including input shapes, output shapes, and explanations:
**Notes:**
* concatenate requires the shapes to match in all axes except the concatenation axis.
* stack requires the shapes to be exactly the same and adds a new axis at the specified position.
* The axis number refers to the position in the output array.

##### For 1D arrays concatenate (shape like (N,)):
| Function        | Input shapes   | Output shape | Explanation                    |
| --------------- | -------------- | ------------ | ------------------------------ |
| `concatenate`   | `(3,)`, `(3,)` | `(6,)`       | Joins arrays end-to-end        |

* Concate do not creat new axis


In [2]:
import numpy as np

In [3]:
a = np.array([1, 2])
b = np.array([3,4])

In [4]:
#concatenate axis = 0
arr= np.concatenate((a,b))  # Deault axis = 0
arr

array([1, 2, 3, 4])

In [5]:
arr= np.hstack((a,b))  # Deault axis = 0
arr

array([1, 2, 3, 4])

In [6]:
# Stacking arrays axis = 0
arr= np.stack((a,b))  # Default axis = 0
arr

array([[1, 2],
       [3, 4]])

In [7]:
arr= np.vstack((a,b))  # Deault axis = 0
arr

array([[1, 2],
       [3, 4]])

In [8]:
# Stacking arrays axis = 1
arr= np.vstack((a,b), axis=1)
arr

TypeError: vstack() got an unexpected keyword argument 'axis'

In [9]:
# Stacking arrays axis = 1
arr= np.dstack((a,b))
arr

array([[[1, 3],
        [2, 4]]])

In [ ]:
# Defining 2 1D arrays Shape(3)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
arr= np.concatenate((a,b))  # Default axis = 0
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
#concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

arr= np.concatenate((a,b), axis = 1)
arr

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
#concatenate
a = np.array([1, 2])
b = np.array([3,4])

arr= np.stack((a,b), axis=1)
arr

array([[1, 3],
       [2, 4]])

In [ ]:
#concatenate
a = np.array([1, 2])
b = np.array([3,4])

arr= np.vstack((a,b))  # Deault axis = 0
arr

array([[1, 2],
       [3, 4]])

##### For 2D arrays concatenate (shape like (M, N)):
| Function              | Input shapes       | Output shape | Explanation                                     |
| --------------------- | ------------------ | ------------ | ----------------------------------------------- |
| `concatenate(axis=0)` | `(2, 3)`, `(2, 3)` | `(4, 3)`     | Stack vertically (add rows)                     |
| `concatenate(axis=1)` | `(2, 3)`, `(2, 3)` | `(2, 6)`     | Stack horizontally (add columns)                |

In [ ]:
# Concatenate axis = 0
a2= [[1,2,3],[5,6,7]]  # shape (2,3)
b2 = [[8,9,10],[11,12,13]]  # shape (2,3)

arr= np.concatenate((a2,b2))    # Default axis = 0
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
# Concatenate axis = 1
arr= np.concatenate((a2,b2), axis = 1)
arr

array([[ 1,  2,  3,  8,  9, 10],
       [ 5,  6,  7, 11, 12, 13]])

In [ ]:
# Concatenate axis = 2
arr= np.concatenate((a2,b2), axis = 2)
arr

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
x2=np.array([[1,2,3],
            [4,5,6]])   # Shape (2, 3)
y2=np.array([[7,8,9],
            [10,11,12]])  # Shape (2, 3)
z2=np.array([[13,14,15],
            [16,17,18]])  # Shape (2, 3)

In [ ]:
arr= np.concatenate((x2,y2,z2))    # Default axis = 0
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
arr= np.concatenate((x2,y2,z2), axis=1)  # Concatenate along axis 1
arr

array([[ 1,  2,  3,  7,  8,  9, 13, 14, 15],
       [ 4,  5,  6, 10, 11, 12, 16, 17, 18]])

##### For 3D arrays concatenate (shape like (L, M, N)):
| Function              | Input shapes             | Output shape   | Explanation                           |
| --------------------- | ------------------------ | -------------- | ------------------------------------- |
| `concatenate(axis=0)` | `(2, 3, 4)`, `(2, 3, 4)` | `(4, 3, 4)`    | Stack along first dimension (depth)   |
| `concatenate(axis=1)` | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 6, 4)`    | Stack along second dimension (rows)   |
| `concatenate(axis=2)` | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 3, 8)`    | Stack along third dimension (columns) |

In [ ]:
# Defining two 3D arrays
m3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],

            [[10,11,12],
            [13,14,15],
            [16,17,18]]])     # Shape (2, 3, 3)

n3=np.array([[[51,52,53],
            [54,55,56],
            [57,58,59]],

            [[110,111,112],
            [113,114,115],
            [116,117,118]]])     # Shape (2, 3, 3)


In [ ]:
# Concatenate along the first axis 
# Shape(4, 3, 3)
arr= np.concatenate((m3,n3))    # Default axis = 0
arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16,  17,  18]],

       [[ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[110, 111, 112],
        [113, 114, 115],
        [116, 117, 118]]])

In [ ]:
# Concatenate axis = 1
# Shape(2, 6, 3)
arr= np.concatenate((m3,n3), axis = 1)
arr

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16,  17,  18],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 118]]])

In [ ]:
# Concatenate axis = 2
# Shape(2, 3, 6)
arr= np.concatenate((m3,n3), axis = 2)
arr

array([[[  1,   2,   3,  51,  52,  53],
        [  4,   5,   6,  54,  55,  56],
        [  7,   8,   9,  57,  58,  59]],

       [[ 10,  11,  12, 110, 111, 112],
        [ 13,  14,  15, 113, 114, 115],
        [ 16,  17,  18, 116, 117, 118]]])

##### For 1D arrays Stack (shape like (N,)):
| Function        | Input shapes   | Output shape | Explanation                    |
| --------------- | -------------- | ------------ | ------------------------------ |
| `stack(axis=0)` | `(3,)`, `(3,)` | `(2, 3)`     | New axis added at front (rows) |
| `stack(axis=1)` | `(3,)`, `(3,)` | `(3, 2)`     | New axis added as columns      |

In [ ]:
# Stack (axis = 0)
a = np.array([1, 2])
b = np.array([3,4])

arr= np.stack((a,b))
arr

array([[1, 2],
       [3, 4]])

In [ ]:
# Stack (axis = 1)
a = np.array([1, 2])
b = np.array([3,4])

arr= np.stack((a,b), axis = 1)
arr

array([[1, 3],
       [2, 4]])

In [ ]:
# Stack (axis = 1)
a = np.array([1, 2])
b = np.array([3,4])

arr= np.hstack((a,b))
arr

array([1, 2, 3, 4])

In [ ]:
# Stack (axis = 1)
a = np.array([1, 2])
b = np.array([3,4])

arr= np.vstack((a,b))
arr

array([[1, 2],
       [3, 4]])

In [ ]:
# Stack (axis = 1)
a = np.array([1, 2])
b = np.array([3,4])

arr= np.dstack((a,b))
arr

array([[[1, 3],
        [2, 4]]])

##### For 2D arrays stack (shape like (M, N)):
| Function              | Input shapes       | Output shape | Explanation                                     |
| --------------------- | ------------------ | ------------ | ----------------------------------------------- |
| `stack(axis=0)`       | `(2, 3)`, `(2, 3)` | `(2, 2, 3)`  | Add new axis at front, stacks arrays depth-wise |
| `stack(axis=1)`       | `(2, 3)`, `(2, 3)` | `(2, 2, 3)`  | Add new axis at axis=1                          |
| `stack(axis=2)`       | `(2, 3)`, `(2, 3)` | `(2, 3, 2)`  | Add new axis at axis=2 (depth-wise)             |

##### For 3D arrays stack (shape like (L, M, N)):
| Function              | Input shapes             | Output shape   | Explanation                           |
| --------------------- | ------------------------ | -------------- | ------------------------------------- |
| `stack(axis=0)`       | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 2, 3, 4)` | Add new axis at front                 |
| `stack(axis=1)`       | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 2, 3, 4)` | Add new axis at axis=1                |
| `stack(axis=2)`       | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 3, 2, 4)` | Add new axis at axis=2                |
| `stack(axis=3)`       | `(2, 3, 4)`, `(2, 3, 4)` | `(2, 3, 4, 2)` | Add new axis at axis=3                |