In [2]:
import numpy as np

In [3]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [5]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [6]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [7]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [8]:
arr = np.array([[5, 0, 1],[3, 2, 4]])
print(np.sort(arr))

[[0 1 5]
 [2 3 4]]
